#!/bin/bash

# Check if the script is run with sudo
if [ "$EUID" -ne 0 ]; then
    echo "#############################################"
    echo "# Please run this script with sudo.         #"
    echo "# Example: sudo bash ./install              #"
    echo "#############################################"
    printf "\n\n"
    exit 1
fi

# Check if ascii-image-converter is installed
repo_url="https://github.com/TheZoraiz/ascii-image-converter"
if ! command -v ascii-image-converter &>/dev/null; then
    echo "ascii-image-converter could not be found. Please install it first."
    printf "\e[4m%s\e[0m" "$repo_url" # underlined
    exit 1
fi

# Create the hidden directory if it doesn't already exist
mkdir -p "$HOME"/.my-corporate-bash/

# Copy the main script to /usr/local/bin
cp ./my-corporate-bash.sh /usr/local/bin/my-corporate-bash
cp ./run.sh "$HOME"/.my-corporate-bash/run.sh

cp ./setup.sh "$HOME"/.my-corporate-bash/setup.sh
cp ./uninstall.sh "$HOME"/.my-corporate-bash/uninstall.sh
cp ./enable.sh "$HOME"/.my-corporate-bash/enable.sh
cp ./disable.sh "$HOME"/.my-corporate-bash/disable.sh
cp ./clear_bash.sh "$HOME"/.my-corporate-bash/clear_bash.sh

# Give execute permissions
chmod +x /usr/local/bin/my-corporate-bash
chmod +x "$HOME"/.my-corporate-bash/run.sh
chmod +x "$HOME"/.my-corporate-bash/setup.sh
chmod +x "$HOME"/.my-corporate-bash/uninstall.sh
chmod +x "$HOME"/.my-corporate-bash/enable.sh
chmod +x "$HOME"/.my-corporate-bash/disable.sh
chmod +x "$HOME"/.my-corporate-bash/clear_bash.sh

# Change the owner of the directory to the current user
sudo chown -R "$SUDO_USER":staff "$HOME"/.my-corporate-bash/

echo "Installation completed. You can now use 'my-corporate-bash'."
